### PR TITLE
Do not autogenerate lint.xml for clients

### PR DESCRIPTION
**Pull request by f2rf2r**

### CODE REVIEW

**Comment by gdaniels** [comment]
Does this affect the IDE's ability to understand the custom rules in any way?  I.e. are there yellow gutter markers that might not show up if the file isn't called "lint.xml"?

**Comment by f2rf2r** [comment]
looks like the IDE requires the file to be called "lint.xml" and under the project directory. so we would need to go back to copying the lint file, but without the if file.exists check. However, we don't want it to run every time gradle syncs since it's a waste, so other possible options are:
1.  provide a different gradle command that explicty copies/updates the lint.xml file
2. only do the copy/update when lint is run
3. perhaps do some sort the checksum or date check, but I'm not sure how efficient (checvksum) or accurate (date) this would be

**Comment by gdaniels** [comment]
The date based approach should work.  We could also just pop a version number at the beginning of the lint.xml in a comment to avoid reading the whole file.

**Comment by f2rf2r** [comment]
It will still cause a lot of wasted cycles given how rare is it for the lint rules to be updated compared to just doing a normal build or gradle sync. I'm leaning towards option 1. It's also kinda beneficial to allow people to update the static plugin version independently of lint rules.

**Pull request closed without merging**
